param(
  [string]$ClaspUser = "default",
  [switch]$RotateLaunchSeal
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path $PSScriptRoot -Parent
$CmsRoot = Join-Path $RepoRoot "apps-script\media-cms"
$ProjectFile = Join-Path $CmsRoot ".clasp.json"
$BindingFile = Join-Path $CmsRoot "MMJRuntimeBinding05PGR2.generated.gs"
$LaunchSealFile = Join-Path $CmsRoot "MMJRuntimeLaunchSeal05PGR2.generated.gs"
$ReceiptFile = Join-Path $RepoRoot "artifacts\MMJ_05P_G_R2_DEPLOYMENT_RECEIPT.local.json"
$PredeployLogFile = Join-Path $RepoRoot "artifacts\MMJ_05P_G_R2_PREDEPLOY_GATE.local.log"
$Description = "MMJ-05P-G-R2 existing-bound-owner-webapp"

function Assert-CommandAvailable {
  param([string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "E_MMJ_G_R2_COMMAND_MISSING: $Name"
  }
}

function Invoke-Clasp {
  param([string[]]$Arguments)
  $output = & clasp @Arguments 2>&1
  if ($LASTEXITCODE -ne 0) {
    throw "clasp $($Arguments -join ' ') failed:`n$($output -join [Environment]::NewLine)"
  }
  return @($output)
}

function Get-Sha256Hex {
  param([string]$Value)
  $algorithm = [Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [Text.Encoding]::UTF8.GetBytes($Value)
    $hash = $algorithm.ComputeHash($bytes)
    return ([BitConverter]::ToString($hash)).Replace('-', '').ToLowerInvariant()
  } finally {
    $algorithm.Dispose()
  }
}

function New-Base64UrlKey {
  $bytes = New-Object byte[] 32
  $generator = [Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $generator.GetBytes($bytes)
  } finally {
    $generator.Dispose()
  }
  return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Read-ExistingLaunchKey {
  param([string]$Path)
  if (-not (Test-Path $Path)) { return $null }
  $source = Get-Content $Path -Raw
  $match = [regex]::Match($source, "key:\s*'([A-Za-z0-9_-]{32,})'")
  if (-not $match.Success) { return $null }
  $key = $match.Groups[1].Value
  if ($key.StartsWith('__MMJ_')) { return $null }
  return $key
}

function Find-DeploymentId {
  param([string[]]$Lines, [string]$Marker)
  foreach ($line in $Lines) {
    if ($line -notlike "*$Marker*") { continue }
    $match = [regex]::Match($line, '(AKfy[A-Za-z0-9_-]{20,})')
    if ($match.Success) { return $match.Groups[1].Value }
  }
  return $null
}

function Test-DeploymentPresent {
  param([string[]]$Lines, [string]$DeploymentId)
  if (-not $DeploymentId) { return $false }
  $escaped = [regex]::Escape($DeploymentId)
  return [bool]($Lines | Where-Object { $_ -match $escaped } | Select-Object -First 1)
}

Assert-CommandAvailable "node"
Assert-CommandAvailable "npm"
Assert-CommandAvailable "clasp"

if (-not (Test-Path $ProjectFile)) {
  throw "E_MMJ_G_R2_EXISTING_CLASP_PROJECT_MISSING: $ProjectFile"
}

Set-Location $RepoRoot

$cleanupOutput = & node "scripts/mmj-05p-g-r2-migrate-g-r1-residue.mjs" --apply 2>&1
$cleanupExitCode = $LASTEXITCODE
$cleanupOutput | ForEach-Object { Write-Host $_ }
if ($cleanupExitCode -ne 0) {
  throw "E_MMJ_G_R2_G_R1_RESIDUE_MIGRATION_FAILED"
}

$predeployLogDirectory = Split-Path $PredeployLogFile -Parent
New-Item -ItemType Directory -Path $predeployLogDirectory -Force | Out-Null
$gateOutput = & node "scripts/mmj-05p-g-r2-run-predeploy-gate.mjs" 2>&1
$gateExitCode = $LASTEXITCODE
$gateOutput | Set-Content -Path $PredeployLogFile -Encoding UTF8
$gateOutput | ForEach-Object { Write-Host $_ }
if ($gateExitCode -ne 0) {
  $tail = @($gateOutput | Select-Object -Last 40) -join [Environment]::NewLine
  throw "MMJ-05P-G-R2 predeploy gate failed. Full log: $PredeployLogFile`n--- gate tail ---`n$tail"
}

$metadataJson = & node "scripts/mmj-05p-g-r2-resolve-bound-parent.mjs" --project $ProjectFile --user $ClaspUser
if ($LASTEXITCODE -ne 0) {
  throw "E_MMJ_G_R2_BOUND_PARENT_RESOLUTION_FAILED: $metadataJson"
}
$metadata = $metadataJson | ConvertFrom-Json
$scriptId = [string]$metadata.scriptId
$workbookId = [string]$metadata.parentId
$scriptIdSha256 = Get-Sha256Hex $scriptId
$launchKey = if ($RotateLaunchSeal) { $null } else { Read-ExistingLaunchKey $LaunchSealFile }
if (-not $launchKey) { $launchKey = New-Base64UrlKey }

$bindingSource = @"
// Generated by scripts/deploy-mmj-05p-g-r2-existing-bound.ps1.
var MMJ_RUNTIME_BINDING_05P_G_R2 = Object.freeze({
  schemaVersion: 1,
  revision: 'MMJ-05P-G-R2',
  bindingMode: 'apps-script-api-project-parent-id',
  workbookId: '$workbookId',
  scriptIdSha256: '$scriptIdSha256'
});
"@
[IO.File]::WriteAllText($BindingFile, $bindingSource, (New-Object Text.UTF8Encoding($false)))

$launchSource = @"
// Generated by scripts/deploy-mmj-05p-g-r2-existing-bound.ps1.
var MMJ_RUNTIME_LAUNCH_SEAL_05P_G_R2 = Object.freeze({
  schemaVersion: 1,
  revision: 'MMJ-05P-G-R2',
  issuer: 'mmj-bound-sidebar',
  audience: 'mmj-owner-webapp',
  key: '$launchKey'
});
"@
[IO.File]::WriteAllText($LaunchSealFile, $launchSource, (New-Object Text.UTF8Encoding($false)))

& node "scripts/mmj-05p-g-r2-existing-bound-owner-webapp-gate.mjs" --sealed
if ($LASTEXITCODE -ne 0) { throw "MMJ-05P-G-R2 sealed gate failed." }

Set-Location $CmsRoot
Invoke-Clasp @('push', '--force') | ForEach-Object { Write-Host $_ }

$existing = Invoke-Clasp @('deployments')
$deploymentId = $null
if (Test-Path $ReceiptFile) {
  try {
    $receipt = Get-Content $ReceiptFile -Raw | ConvertFrom-Json
    $receiptDeploymentId = [string]$receipt.deploymentId
    if (
      [string]$receipt.scriptId -eq $scriptId -and
      (Test-DeploymentPresent $existing $receiptDeploymentId)
    ) {
      $deploymentId = $receiptDeploymentId
    }
  } catch {
    $deploymentId = $null
  }
}

if (-not $deploymentId) {
  $deploymentId = Find-DeploymentId $existing $Description
}

if ($deploymentId) {
  Invoke-Clasp @('deploy', '--deploymentId', $deploymentId, '--description', $Description) | ForEach-Object { Write-Host $_ }
} else {
  Invoke-Clasp @('deploy', '--description', $Description) | ForEach-Object { Write-Host $_ }
}

$deployments = Invoke-Clasp @('deployments')
$deploymentId = Find-DeploymentId $deployments $Description
if (-not $deploymentId) {
  throw "E_MMJ_G_R2_DEPLOYMENT_ID_NOT_FOUND: deployment completed but the marked deployment could not be resolved."
}

$receiptDirectory = Split-Path $ReceiptFile -Parent
New-Item -ItemType Directory -Path $receiptDirectory -Force | Out-Null
$receipt = [ordered]@{
  schemaVersion = 1
  revision = 'MMJ-05P-G-R2'
  scriptId = $scriptId
  scriptIdSha256 = $scriptIdSha256
  workbookIdSha256 = Get-Sha256Hex $workbookId
  deploymentId = $deploymentId
  webAppUrl = "https://script.google.com/macros/s/$deploymentId/exec"
  executeAs = 'USER_DEPLOYING'
  access = 'ANYONE'
  manualAppsScriptFunctionExecutions = 0
  deployedAt = [DateTime]::UtcNow.ToString('o')
}
$receipt | ConvertTo-Json -Depth 5 | Set-Content -Path $ReceiptFile -Encoding utf8

Set-Location $RepoRoot
& node "scripts/mmj-05p-g-r2-existing-bound-owner-webapp-gate.mjs" --sealed
if ($LASTEXITCODE -ne 0) { throw "MMJ-05P-G-R2 final gate failed." }

Write-Host "PASS_MMJ_05P_G_R2_EXISTING_BOUND_OWNER_WEBAPP_DEPLOYMENT"
Write-Host "Script ID preserved: $scriptId"
Write-Host "Workbook parent sealed from Apps Script API metadata."
Write-Host "Web app: https://script.google.com/macros/s/$deploymentId/exec"
