import type {
  CommissionGuideContent,
} from '~~/shared/types/commission-guide'

export const COMMISSION_GUIDE_MOCK = {
  schemaVersion: 10,

  eyebrow: 'Commission Guide',
  title: '의뢰 안내',
  lead:
    '서비스별 작업 범위와 기본 견적 기준을 확인할 수 있습니다.',
  seoTitle: '의뢰 안내 | 매미: 著',
  seoDescription:
    '안무, 작사·작곡, 의상 디자인·제작, 영상기획, 프로젝트 기획, 믹싱·마스터링 의뢰 범위와 견적 기준을 안내합니다.',

  sectionHeading: '의뢰 분야',
  services: [
    {
      id: 'choreography',
      order: 10,
      enabled: true,
      label: '안무',
      summary: '곡과 무대의 흐름에 맞춘 안무 설계',
      description:
        '곡의 길이와 참여 인원을 기준으로 한 안무 창작 기본 비용입니다.',
      excludedGlobalTermIds: [],
      pricing: {
        kind: 'matrix',
        title: '안무 창작 기본 가격표',
        description:
          '곡 길이와 참여 인원을 기준으로 한 기본 비용이며, 최종 금액은 작업 조건을 확인한 뒤 확정합니다.',
        compactDescription:
          '곡 길이·참여 인원 기준 · 최종 금액은 상담 후 확정',
        currency: 'KRW',
        displayUnit: 'manwon',
        unitLabel: '만원 · 부가세 포함',
        rowAxisLabel: '참여 인원',
        columnAxisLabel: '곡 길이',
        columns: [
          {
            id: 'short-form-30s',
            order: 10,
            enabled: true,
            label: '숏폼 에디션',
            detailLabel: '30초 이하',
            shortLabel: '30초 이하',
          },
          {
            id: 'edited-half-1-2m',
            order: 20,
            enabled: true,
            label: '반절 정도로 편집된 곡',
            detailLabel: '1~2분 내외',
            shortLabel: '1~2분 내외',
          },
          {
            id: 'full-3m',
            order: 30,
            enabled: true,
            label: '풀곡',
            detailLabel: '3분 내외',
            shortLabel: '3분 내외',
          },
          {
            id: 'full-3m30-plus',
            order: 40,
            enabled: true,
            label: '풀곡',
            detailLabel: '3분 30초 이상',
            shortLabel: '3분 30초 이상',
          },
        ],
        rows: [
          {
            id: 'solo',
            order: 10,
            enabled: true,
            label: '1인',
            detailLabel: null,
            shortLabel: '1인',
          },
          {
            id: 'duo',
            order: 20,
            enabled: true,
            label: '2인',
            detailLabel: '동선 구성 포함',
            shortLabel: '2인',
          },
          {
            id: 'group-3-plus',
            order: 30,
            enabled: true,
            label: '3인 이상',
            detailLabel: '동선 구성 포함',
            shortLabel: '3인',
          },
        ],
        cells: [
          { rowId: 'solo', columnId: 'short-form-30s', mode: 'from', amountKrw: 20_000, displayOverride: null, note: null },
          { rowId: 'solo', columnId: 'edited-half-1-2m', mode: 'from', amountKrw: 50_000, displayOverride: null, note: null },
          { rowId: 'solo', columnId: 'full-3m', mode: 'from', amountKrw: 70_000, displayOverride: null, note: null },
          { rowId: 'solo', columnId: 'full-3m30-plus', mode: 'from', amountKrw: 90_000, displayOverride: null, note: null },
          { rowId: 'duo', columnId: 'short-form-30s', mode: 'from', amountKrw: 40_000, displayOverride: null, note: null },
          { rowId: 'duo', columnId: 'edited-half-1-2m', mode: 'from', amountKrw: 100_000, displayOverride: null, note: null },
          { rowId: 'duo', columnId: 'full-3m', mode: 'from', amountKrw: 140_000, displayOverride: null, note: null },
          { rowId: 'duo', columnId: 'full-3m30-plus', mode: 'from', amountKrw: 180_000, displayOverride: null, note: null },
          { rowId: 'group-3-plus', columnId: 'short-form-30s', mode: 'from', amountKrw: 50_000, displayOverride: null, note: null },
          { rowId: 'group-3-plus', columnId: 'edited-half-1-2m', mode: 'from', amountKrw: 120_000, displayOverride: null, note: null },
          { rowId: 'group-3-plus', columnId: 'full-3m', mode: 'from', amountKrw: 170_000, displayOverride: null, note: null },
          { rowId: 'group-3-plus', columnId: 'full-3m30-plus', mode: 'from', amountKrw: 220_000, displayOverride: null, note: null },
        ],
        fullSpanCells: [],
        footnote:
          '표의 금액은 기본 기준이며 용도, 마감 일정과 수정 범위에 따라 조정될 수 있습니다.',
        mock: true,
      },
      includedItems: [
        '구성 방향 협의',
        '메인 동작 설계',
        '2인 이상 동선 구성',
        '기본 수정',
      ],
      turnaroundLabel: '일정과 곡 길이 확인 후 협의',
      revisionLabel: '기본 수정 범위는 착수 전 협의',
      additionalCostNote:
        '용도, 긴급 일정과 협의 범위를 넘어서는 수정은 추가 비용이 발생할 수 있습니다.',
      inquiryLabel: '안무 의뢰 문의하기',
    },
    {
      id: 'lyrics-composition',
      order: 20,
      enabled: true,
      label: '작사/작곡',
      summary: '콘셉트와 사용 목적에 맞춘 음원 제작',
      description:
        '곡의 콘셉트와 사용 목적에 맞춰 작사, 작곡 또는 두 작업을 함께 진행합니다.',
      excludedGlobalTermIds: [],
      pricing: {
        kind: 'matrix-set',
        title: '작사/작곡 기본 가격표',
        description: null,
        compactDescription: null,
        currency: 'KRW',
        displayUnit: 'manwon',
        unitLabel: '만원 · 부가세 포함',
        sharedGuidanceHeading: '구성방식',
        sharedGuidanceItems: [
          {
            id: 'lyrics-composition-regular-structure',
            order: 10,
            enabled: true,
            label: '일반 구성',
            description: '1절/2절처럼 반복성 있는 구성',
          },
          {
            id: 'lyrics-composition-musical-edition',
            order: 20,
            enabled: true,
            label: '뮤지컬 에디션',
            description: '반복성이 없고 형식에 구애받지 않는 구성',
          },
          {
            id: 'lyrics-composition-delivery-files',
            order: 30,
            enabled: true,
            label: '제공 파일',
            description: 'inst 파일 + 탑라인 보컬 가이드 파일 + 가사 파일 제공',
          },
          {
            id: 'lyrics-composition-synth-vocal-guide',
            order: 40,
            enabled: true,
            label: '보컬 가이드',
            description: '보컬 가이드는 어울리는 음성합성엔진으로 조교해서 제공',
          },
        ],
        groups: [
          {
            id: 'theme-composition',
            order: 10,
            enabled: true,
            label: '테마곡 작곡',
            shortLabel: '테마곡',
            rowAxisLabel: '편성 기준',
            columnAxisLabel: '곡 길이',
            columns: [
              { id: 'shortform-up-to-1m', order: 10, enabled: true, label: '숏폼에디션', detailLabel: '1분 이하', shortLabel: '1분 이하' },
              { id: 'short-song-up-to-2m', order: 20, enabled: true, label: '짧은 곡', detailLabel: '2분 내외', shortLabel: '2분 내외' },
              { id: 'general-theme-up-to-3m', order: 30, enabled: true, label: '일반 테마곡', detailLabel: '3분 내외', shortLabel: '3분 내외' },
              { id: 'long-theme-5m-plus', order: 40, enabled: true, label: '긴 테마곡', detailLabel: '5분 이상', shortLabel: '5분 이상' },
            ],
            rows: [
              { id: 'instrument-up-to-3', order: 10, enabled: true, label: '악기 3개 이하', detailLabel: null },
              { id: 'instrument-up-to-10', order: 20, enabled: true, label: '악기 10개 이하', detailLabel: null },
              { id: 'ppongppongre-omakase', order: 30, enabled: true, label: '빵빠레 오마카세', detailLabel: null },
            ],
            cells: [
              { rowId: 'instrument-up-to-3', columnId: 'shortform-up-to-1m', mode: 'fixed', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-3', columnId: 'short-song-up-to-2m', mode: 'fixed', amountKrw: 40_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-3', columnId: 'general-theme-up-to-3m', mode: 'fixed', amountKrw: 60_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-3', columnId: 'long-theme-5m-plus', mode: 'from', amountKrw: 90_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-10', columnId: 'shortform-up-to-1m', mode: 'fixed', amountKrw: 40_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-10', columnId: 'short-song-up-to-2m', mode: 'fixed', amountKrw: 80_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-10', columnId: 'general-theme-up-to-3m', mode: 'fixed', amountKrw: 120_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-10', columnId: 'long-theme-5m-plus', mode: 'from', amountKrw: 180_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'shortform-up-to-1m', mode: 'from', amountKrw: 80_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'short-song-up-to-2m', mode: 'from', amountKrw: 160_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'general-theme-up-to-3m', mode: 'from', amountKrw: 240_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'long-theme-5m-plus', mode: 'from', amountKrw: 360_000, displayOverride: null, note: null },
            ],
            fullSpanCells: [],
            guidanceItems: [],
          },
          {
            id: 'lyrics-included-composition',
            order: 20,
            enabled: true,
            label: '가사O 작곡',
            shortLabel: '가사O 작곡',
            rowAxisLabel: '편성 기준',
            columnAxisLabel: '곡 구성',
            columns: [
              { id: 'shortform-up-to-1m', order: 10, enabled: true, label: '숏폼에디션', detailLabel: '1분 이하', shortLabel: '1분 이하' },
              { id: 'standard-short-up-to-2m', order: 20, enabled: true, label: '일반 구성 - 숏', detailLabel: '2분 이내', shortLabel: '2분 이내' },
              { id: 'standard-long-up-to-3m', order: 30, enabled: true, label: '일반 구성 - 롱', detailLabel: '3분 내외', shortLabel: '3분 내외' },
              { id: 'musical-edition-min-4m', order: 40, enabled: true, label: '뮤지컬 에디션', detailLabel: '최소 4분 이상', shortLabel: '4분 이상' },
            ],
            rows: [
              { id: 'instrument-up-to-5', order: 10, enabled: true, label: '악기 5개 이하', detailLabel: null },
              { id: 'instrument-up-to-15', order: 20, enabled: true, label: '악기 15개 이하', detailLabel: null },
              { id: 'ppongppongre-omakase', order: 30, enabled: true, label: '빵빠레 오마카세', detailLabel: null },
            ],
            cells: [
              { rowId: 'instrument-up-to-5', columnId: 'shortform-up-to-1m', mode: 'fixed', amountKrw: 30_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-5', columnId: 'standard-short-up-to-2m', mode: 'fixed', amountKrw: 50_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-5', columnId: 'standard-long-up-to-3m', mode: 'fixed', amountKrw: 80_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-5', columnId: 'musical-edition-min-4m', mode: 'from', amountKrw: 120_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'shortform-up-to-1m', mode: 'fixed', amountKrw: 60_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'standard-short-up-to-2m', mode: 'fixed', amountKrw: 100_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'standard-long-up-to-3m', mode: 'fixed', amountKrw: 160_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'musical-edition-min-4m', mode: 'from', amountKrw: 240_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'shortform-up-to-1m', mode: 'from', amountKrw: 100_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'standard-short-up-to-2m', mode: 'from', amountKrw: 160_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'standard-long-up-to-3m', mode: 'from', amountKrw: 250_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'musical-edition-min-4m', mode: 'from', amountKrw: 380_000, displayOverride: null, note: null },
            ],
            fullSpanCells: [],
            guidanceItems: [],
          },
          {
            id: 'lyrics-and-composition',
            order: 30,
            enabled: true,
            label: '작사+작곡',
            shortLabel: '작사+작곡',
            rowAxisLabel: '편성 기준',
            columnAxisLabel: '곡 구성',
            columns: [
              { id: 'shortform-up-to-1m', order: 10, enabled: true, label: '숏폼에디션', detailLabel: '1분 이하', shortLabel: '1분 이하' },
              { id: 'standard-short-up-to-2m', order: 20, enabled: true, label: '일반 구성 - 숏', detailLabel: '2분 이내', shortLabel: '2분 이내' },
              { id: 'standard-long-up-to-3m', order: 30, enabled: true, label: '일반 구성 - 롱', detailLabel: '3분 내외', shortLabel: '3분 내외' },
              { id: 'musical-edition-min-4m', order: 40, enabled: true, label: '뮤지컬 에디션', detailLabel: '최소 4분 이상', shortLabel: '4분 이상' },
            ],
            rows: [
              { id: 'instrument-up-to-5', order: 10, enabled: true, label: '악기 5개 이하', detailLabel: null },
              { id: 'instrument-up-to-15', order: 20, enabled: true, label: '악기 15개 이하', detailLabel: null },
              { id: 'ppongppongre-omakase', order: 30, enabled: true, label: '빵빠레 오마카세', detailLabel: null },
            ],
            cells: [
              { rowId: 'instrument-up-to-5', columnId: 'shortform-up-to-1m', mode: 'fixed', amountKrw: 50_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-5', columnId: 'standard-short-up-to-2m', mode: 'fixed', amountKrw: 80_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-5', columnId: 'standard-long-up-to-3m', mode: 'fixed', amountKrw: 120_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-5', columnId: 'musical-edition-min-4m', mode: 'from', amountKrw: 200_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'shortform-up-to-1m', mode: 'fixed', amountKrw: 100_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'standard-short-up-to-2m', mode: 'fixed', amountKrw: 160_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'standard-long-up-to-3m', mode: 'fixed', amountKrw: 240_000, displayOverride: null, note: null },
              { rowId: 'instrument-up-to-15', columnId: 'musical-edition-min-4m', mode: 'from', amountKrw: 350_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'shortform-up-to-1m', mode: 'from', amountKrw: 180_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'standard-short-up-to-2m', mode: 'from', amountKrw: 280_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'standard-long-up-to-3m', mode: 'from', amountKrw: 400_000, displayOverride: null, note: null },
              { rowId: 'ppongppongre-omakase', columnId: 'musical-edition-min-4m', mode: 'from', amountKrw: 500_000, displayOverride: null, note: null },
            ],
            fullSpanCells: [],
            guidanceItems: [],
          },
        ],
        footnote: null,
        mock: false,
      },
      includedItems: [
        'inst 파일',
        '탑라인 보컬 가이드 파일',
        '가사 파일',
        '음성합성엔진으로 조교한 보컬 가이드',
      ],
      turnaroundLabel: '곡 구성과 작업 범위 확인 후 협의',
      revisionLabel: '초안 확인 뒤 기본 수정 범위 제공',
      additionalCostNote: null,
      inquiryLabel: '작사/작곡 의뢰 문의하기',
    },
    {
      id: 'costume-design-production',
      order: 30,
      enabled: true,
      label: '의상디자인 / 제작',
      summary: '무대와 촬영 콘셉트에 맞춘 의상 설계',
      description:
        '무대와 촬영 콘셉트에 맞춰 의상 방향을 정리하고 디자인 또는 제작 범위를 협의합니다.',
      excludedGlobalTermIds: [],
      pricing: {
        kind: 'matrix-set',
        title: '의상디자인 / 제작 기본 가격표',
        description: null,
        compactDescription: null,
        currency: 'KRW',
        displayUnit: 'manwon',
        unitLabel: '만원 · 부가세 포함',
        sharedGuidanceHeading: null,
        sharedGuidanceItems: [],
        groups: [
          {
            id: 'costume-design',
            order: 10,
            enabled: true,
            label: '의상 디자인',
            shortLabel: '의상 디자인',
            rowAxisLabel: '디자인 범위',
            columnAxisLabel: '의상 스타일',
            columns: [
              { id: 'daily-wear', order: 10, enabled: true, label: '일상복 스타일', detailLabel: null, shortLabel: '일상복' },
              { id: 'hongdae-punk', order: 20, enabled: true, label: '홍대펑크 스타일', detailLabel: null, shortLabel: '홍대펑크' },
              { id: 'concept-stage-costume', order: 30, enabled: true, label: '컨셉/무대의상 스타일', detailLabel: null, shortLabel: '컨셉/무대의상' },
            ],
            rows: [
              { id: 'simple-design', order: 10, enabled: true, label: '간단 디자인', detailLabel: null },
              { id: 'formal-design', order: 20, enabled: true, label: '정식 디자인', detailLabel: null },
            ],
            cells: [
              { rowId: 'simple-design', columnId: 'daily-wear', mode: 'from', amountKrw: 5_000, displayOverride: null, note: null },
              { rowId: 'simple-design', columnId: 'hongdae-punk', mode: 'from', amountKrw: 10_000, displayOverride: null, note: null },
              { rowId: 'simple-design', columnId: 'concept-stage-costume', mode: 'from', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'formal-design', columnId: 'daily-wear', mode: 'from', amountKrw: 10_000, displayOverride: null, note: null },
              { rowId: 'formal-design', columnId: 'hongdae-punk', mode: 'from', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'formal-design', columnId: 'concept-stage-costume', mode: 'from', amountKrw: 40_000, displayOverride: null, note: null },
            ],
            fullSpanCells: [],
            guidanceItems: [
              {
                id: 'simple-design-format',
                order: 10,
                enabled: true,
                label: '의상 간단 디자인',
                description: '정면을 보고있는 MD사이즈 전신 마네킹에 디자인한 의상을 그려서 드리는 형식',
              },
              {
                id: 'formal-design-format',
                order: 20,
                enabled: true,
                label: '의상 정식 디자인',
                description: '정면, 측면, 후면을 보고있는 MD사이즈 전신 마네킹에 디자인한 의상을 그려서 드리는 형식',
              },
              {
                id: 'daily-wear-style',
                order: 30,
                enabled: true,
                label: '일상복 스타일',
                description: '단순하고 디테일이 적음',
              },
              {
                id: 'hongdae-punk-style',
                order: 40,
                enabled: true,
                label: '홍대펑크 스타일',
                description: '화려한 일상복 스타일, 디테일이 많음',
              },
              {
                id: 'concept-stage-costume-style',
                order: 50,
                enabled: true,
                label: '컨셉/무대의상 스타일',
                description: '매우 화려, 디테일 매우 많음',
              },
            ],
          },
          {
            id: 'costume-production',
            order: 20,
            enabled: true,
            label: '의상 제작',
            shortLabel: '의상 제작',
            rowAxisLabel: '제작 기준',
            columnAxisLabel: '제작 종류',
            columns: [
              { id: 'accessory', order: 10, enabled: true, label: '악세사리류', detailLabel: null, shortLabel: '악세사리류' },
              { id: 'costume-reform', order: 20, enabled: true, label: '의상리폼', detailLabel: null, shortLabel: '의상리폼' },
              { id: 'custom-production', order: 30, enabled: true, label: '자체제작', detailLabel: null, shortLabel: '자체제작' },
            ],
            rows: [
              { id: 'per-piece-production-fee', order: 10, enabled: true, label: '피스당 제작비', detailLabel: '재료비 제외' },
            ],
            cells: [
              { rowId: 'per-piece-production-fee', columnId: 'accessory', mode: 'from', amountKrw: 5_000, displayOverride: null, note: null },
              { rowId: 'per-piece-production-fee', columnId: 'costume-reform', mode: 'from', amountKrw: 10_000, displayOverride: null, note: null },
              { rowId: 'per-piece-production-fee', columnId: 'custom-production', mode: 'from', amountKrw: 15_000, displayOverride: null, note: null },
            ],
            fullSpanCells: [],
            guidanceItems: [
              {
                id: 'production-material-cost-excluded',
                order: 10,
                enabled: true,
                label: '재료비 제외',
                description: '의상 제작의 경우 재료비를 제외한 순수 제작비만 표시',
              },
              {
                id: 'production-price-per-piece',
                order: 20,
                enabled: true,
                label: '제작비용은 피스당 계산',
                description: '예: 상의 + 페이크 카라 + 목 리본 = 3피스',
              },
            ],
          },
        ],
        footnote: null,
        mock: false,
      },
      includedItems: [
        '디자인 방향 제안',
        '소재와 부자재 협의',
        '제작 범위 정리',
        '피팅 및 수정 조건 협의',
      ],
      turnaroundLabel: '수량과 소재 수급 일정 확인 후 협의',
      revisionLabel: '디자인 확정 전 수정 범위 협의',
      additionalCostNote: null,
      inquiryLabel: '의상 의뢰 문의하기',
    },
    {
      id: 'video-direction',
      order: 40,
      enabled: true,
      label: '영상기획',
      summary: '촬영 목적에 맞춘 장면 구성과 현장 진행',
      description:
        '촬영 목적과 결과물의 톤에 맞춰 장면 구성, 현장 진행과 디렉션 방향을 설계합니다.',
      excludedGlobalTermIds: [],
      pricing: {
        kind: 'matrix',
        title: '영상기획 기본 가격표',
        description: null,
        compactDescription: null,
        currency: 'KRW',
        displayUnit: 'manwon',
        unitLabel: '만원 · 부가세 포함',
        rowAxisLabel: '영상 기획',
        columnAxisLabel: '영상 유형',
        columns: [
          { id: 'shortform-edition', order: 10, enabled: true, label: '숏폼 에디션', detailLabel: '1분 이하', shortLabel: '숏폼' },
          { id: 'simple-mv', order: 20, enabled: true, label: '간단 MV', detailLabel: '편집된 음악 1곡 분량', shortLabel: '간단 MV' },
          { id: 'music-video', order: 30, enabled: true, label: 'MV', detailLabel: '음악 1곡 분량', shortLabel: 'MV' },
          { id: 'special-video', order: 40, enabled: true, label: '스페셜', detailLabel: '음악 1곡+추가 구성', shortLabel: '스페셜' },
        ],
        rows: [
          { id: 'simple-storyboard', order: 10, enabled: true, label: '간단 콘티', detailLabel: null, shortLabel: '간단 콘티' },
          { id: 'storyboard-coaching', order: 20, enabled: true, label: '콘티+코칭', detailLabel: null, shortLabel: '콘티+코칭' },
          { id: 'on-site-director', order: 30, enabled: true, label: '촬영현장 감독', detailLabel: '출장비 제외 · 시간당', shortLabel: '현장 감독' },
          { id: 'camera-director', order: 40, enabled: true, label: '카메라 감독', detailLabel: '출장비 제외 · 시간당', shortLabel: '카메라 감독' },
          { id: 'simple-video-editing', order: 50, enabled: true, label: '간단 영상 편집', detailLabel: '소스 구매비용 제외 · 분당', shortLabel: '간단 편집' },
          { id: 'advanced-video-editing', order: 60, enabled: true, label: '고급 영상 편집', detailLabel: '소스 구매비용 제외 · 분당', shortLabel: '고급 편집' },
        ],
        cells: [
          { rowId: 'simple-storyboard', columnId: 'shortform-edition', mode: 'from', amountKrw: 10_000, displayOverride: null, note: null },
          { rowId: 'simple-storyboard', columnId: 'simple-mv', mode: 'from', amountKrw: 15_000, displayOverride: null, note: null },
          { rowId: 'simple-storyboard', columnId: 'music-video', mode: 'from', amountKrw: 20_000, displayOverride: null, note: null },
          { rowId: 'simple-storyboard', columnId: 'special-video', mode: 'from', amountKrw: 30_000, displayOverride: null, note: null },
          { rowId: 'storyboard-coaching', columnId: 'shortform-edition', mode: 'from', amountKrw: 20_000, displayOverride: null, note: null },
          { rowId: 'storyboard-coaching', columnId: 'simple-mv', mode: 'from', amountKrw: 30_000, displayOverride: null, note: null },
          { rowId: 'storyboard-coaching', columnId: 'music-video', mode: 'from', amountKrw: 40_000, displayOverride: null, note: null },
          { rowId: 'storyboard-coaching', columnId: 'special-video', mode: 'from', amountKrw: 60_000, displayOverride: null, note: null },
          { rowId: 'on-site-director', columnId: 'shortform-edition', mode: 'fixed', amountKrw: 10_000, displayOverride: '1.0', note: null },
          { rowId: 'on-site-director', columnId: 'simple-mv', mode: 'fixed', amountKrw: 20_000, displayOverride: '2.0', note: null },
          { rowId: 'on-site-director', columnId: 'music-video', mode: 'fixed', amountKrw: 30_000, displayOverride: '3.0', note: null },
          { rowId: 'on-site-director', columnId: 'special-video', mode: 'fixed', amountKrw: 40_000, displayOverride: '4.0', note: null },
          { rowId: 'camera-director', columnId: 'shortform-edition', mode: 'fixed', amountKrw: 10_000, displayOverride: '1.0', note: null },
          { rowId: 'camera-director', columnId: 'simple-mv', mode: 'not-listed', amountKrw: null, displayOverride: null, note: null },
          { rowId: 'camera-director', columnId: 'music-video', mode: 'fixed', amountKrw: 20_000, displayOverride: '2.0', note: null },
          { rowId: 'camera-director', columnId: 'special-video', mode: 'not-listed', amountKrw: null, displayOverride: null, note: null },
        ],
        fullSpanCells: [
          {
            rowId: 'simple-video-editing',
            mode: 'from',
            amountKrw: 10_000,
            displayOverride: null,
            note: null,
          },
          {
            rowId: 'advanced-video-editing',
            mode: 'from',
            amountKrw: 20_000,
            displayOverride: null,
            note: null,
          },
        ],
        footnote: null,
        mock: false,
      },
      includedItems: [
        '촬영 구성안',
        '현장 디렉션',
        '컷 진행 관리',
        '후반 작업 인계 정리',
      ],
      turnaroundLabel: '촬영일과 준비 범위 확인 후 협의',
      revisionLabel: '촬영 전 구성안 수정 범위 협의',
      additionalCostNote: null,
      inquiryLabel: '영상기획 의뢰 문의하기',
    },
    {
      id: 'project-planning',
      order: 50,
      enabled: true,
      label: '프로젝트 기획',
      summary: '목표, 일정과 역할을 연결하는 제작 구조 설계',
      description:
        '프로젝트의 목표와 일정, 참여자의 역할을 정리하고 실제 제작이 굴러갈 수 있는 흐름을 설계합니다.',
      excludedGlobalTermIds: [],
      pricing: {
        kind: 'matrix-set',
        title: '프로젝트 기획 기본 가격표',
        description: null,
        compactDescription: null,
        currency: 'KRW',
        displayUnit: 'manwon',
        unitLabel: '만원 · 부가세 포함',
        sharedGuidanceHeading: '조언 / 피드백',
        sharedGuidanceItems: [
          {
            id: 'advice-feedback-format',
            order: 10,
            enabled: true,
            label: '조언 / 피드백',
            description: '이미 있는 기획형태를 검토하고 방향성을 제시하는 형식',
          },
          {
            id: 'simple-concept-format',
            order: 20,
            enabled: true,
            label: '간단 구상',
            description: '아이디어를 제공하고 아이디어에 적합한 팁들을 함께 제공하는 형식',
          },
          {
            id: 'full-planning-format',
            order: 30,
            enabled: true,
            label: '단순 기획',
            description: '원하는 추구미만 제시받고 그에 맞는 기획 전반을 도맡아 제공하는 형식',
          },
          {
            id: 'continuous-feedback-format',
            order: 40,
            enabled: true,
            label: '지속적인 피드백',
            description: '코칭받은 프로젝트를 진행함에 있어서 주기적인 모니터링 및 진행 상황에 따른 피드백 제공',
          },
          {
            id: 'continuous-feedback-order-condition',
            order: 50,
            enabled: true,
            label: '지속적인 피드백 의뢰 조건',
            description: '지속적인 피드백 단독 의뢰 불가 · 다른 기획 형태를 함께 의뢰 가능',
          },
        ],
        groups: [
          {
            id: 'project-planning-default',
            order: 10,
            enabled: true,
            label: '프로젝트 기획',
            shortLabel: '프로젝트 기획',
            rowAxisLabel: '프로젝트 기획',
            columnAxisLabel: '프로젝트 유형',
            columns: [
              { id: 'one-off-project', order: 10, enabled: true, label: '일회성 프로젝트', detailLabel: null, shortLabel: '일회성' },
              { id: 'short-term-project', order: 20, enabled: true, label: '단기 프로젝트', detailLabel: null, shortLabel: '단기' },
              { id: 'long-term-project', order: 30, enabled: true, label: '장기 프로젝트', detailLabel: null, shortLabel: '장기' },
              { id: 'team-formation', order: 40, enabled: true, label: '팀 결성', detailLabel: null, shortLabel: '팀 결성' },
            ],
            rows: [
              { id: 'advice-feedback', order: 10, enabled: true, label: '조언 / 피드백', detailLabel: null, shortLabel: '조언/피드백' },
              { id: 'simple-concept', order: 20, enabled: true, label: '간단 구상', detailLabel: null, shortLabel: '간단 구상' },
              { id: 'full-planning', order: 30, enabled: true, label: '단순 기획', detailLabel: null, shortLabel: '단순 기획' },
              { id: 'continuous-feedback', order: 40, enabled: true, label: '지속적인 피드백', detailLabel: null, shortLabel: '지속 피드백' },
            ],
            cells: [
              { rowId: 'advice-feedback', columnId: 'one-off-project', mode: 'fixed', amountKrw: 10_000, displayOverride: null, note: null },
              { rowId: 'advice-feedback', columnId: 'short-term-project', mode: 'fixed', amountKrw: 10_000, displayOverride: null, note: null },
              { rowId: 'advice-feedback', columnId: 'long-term-project', mode: 'fixed', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'advice-feedback', columnId: 'team-formation', mode: 'fixed', amountKrw: 10_000, displayOverride: null, note: null },
              { rowId: 'simple-concept', columnId: 'one-off-project', mode: 'fixed', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'simple-concept', columnId: 'short-term-project', mode: 'fixed', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'simple-concept', columnId: 'long-term-project', mode: 'fixed', amountKrw: 30_000, displayOverride: null, note: null },
              { rowId: 'simple-concept', columnId: 'team-formation', mode: 'fixed', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'full-planning', columnId: 'one-off-project', mode: 'from', amountKrw: 10_000, displayOverride: null, note: null },
              { rowId: 'full-planning', columnId: 'short-term-project', mode: 'from', amountKrw: 20_000, displayOverride: null, note: null },
              { rowId: 'full-planning', columnId: 'long-term-project', mode: 'from', amountKrw: 30_000, displayOverride: null, note: null },
              { rowId: 'full-planning', columnId: 'team-formation', mode: 'from', amountKrw: 20_000, displayOverride: null, note: null },
            ],
            fullSpanCells: [
              {
                rowId: 'continuous-feedback',
                mode: 'recurring-from',
                weeklyAmountKrw: 10_000,
                monthlyAmountKrw: 40_000,
                note: null,
              },
            ],
            guidanceItems: [],
          },
        ],
        footnote: null,
        mock: false,
      },
      includedItems: [
        '기획 구조 정리',
        '일정 설계',
        '역할과 협업 흐름 정리',
        '진행 문서 구성',
      ],
      turnaroundLabel: '프로젝트 규모와 마감일 확인 후 협의',
      revisionLabel: '기획안 기준 기본 수정 범위 협의',
      additionalCostNote: null,
      inquiryLabel: '프로젝트 기획 문의하기',
    },
    {
      id: 'mixing-mastering',
      order: 60,
      enabled: true,
      label: '믹싱 / 마스터링',
      summary: '음원 밸런스 정리와 최종 출력',
      description:
        '보컬과 반주의 밸런스를 정리하고 최종 사용 환경에 맞춰 음원을 출력합니다.',
      excludedGlobalTermIds: [],
      pricing: {
        kind: 'matrix-set',
        title: '믹싱 / 마스터링 기본 가격표',
        description: null,
        compactDescription: null,
        currency: 'KRW',
        displayUnit: 'manwon',
        unitLabel: '만원 · 부가세 포함',
        sharedGuidanceHeading: '참고사항',
        sharedGuidanceItems: [
          {
            id: 'mixing-track-count-pricing-reference',
            order: 10,
            enabled: true,
            label: '인원수 및 트랙 수 기준',
            description:
              '3인 이상의 인원수도 가능하며, 인원 수보다는 실제 트랙 수에 따라 가격이 조정되기 때문에 예시로 명시된 가격과 차이가 있을 수 있습니다.',
          },
        ],
        groups: [
          {
            id: 'mixing-mastering-default',
            order: 10,
            enabled: true,
            label: '믹싱 / 마스터링',
            shortLabel: '믹싱 / 마스터링',
            rowAxisLabel: '믹싱 / 마스터링',
            columnAxisLabel: '인원 및 트랙 수',
            columns: [
              {
                id: 'one-person-two-tracks',
                order: 10,
                enabled: true,
                label: '1인',
                detailLabel: '2트랙',
                shortLabel: '1인 · 2트랙',
              },
              {
                id: 'two-people-six-tracks',
                order: 20,
                enabled: true,
                label: '2인',
                detailLabel: '6트랙',
                shortLabel: '2인 · 6트랙',
              },
            ],
            rows: [
              {
                id: 'editing-tone-beat',
                order: 10,
                enabled: true,
                label: '에디팅 (톤, 박)',
                detailLabel: null,
                shortLabel: '에디팅',
              },
              {
                id: 'mixing-mastering-work',
                order: 20,
                enabled: true,
                label: '믹싱 / 마스터링',
                detailLabel: null,
                shortLabel: '믹싱/마스터링',
              },
            ],
            cells: [
              {
                rowId: 'editing-tone-beat',
                columnId: 'one-person-two-tracks',
                mode: 'fixed',
                amountKrw: 30_000,
                displayOverride: '3.0',
                note: null,
              },
              {
                rowId: 'editing-tone-beat',
                columnId: 'two-people-six-tracks',
                mode: 'fixed',
                amountKrw: 60_000,
                displayOverride: '6.0',
                note: null,
              },
              {
                rowId: 'mixing-mastering-work',
                columnId: 'one-person-two-tracks',
                mode: 'fixed',
                amountKrw: 30_000,
                displayOverride: '3.0',
                note: null,
              },
              {
                rowId: 'mixing-mastering-work',
                columnId: 'two-people-six-tracks',
                mode: 'fixed',
                amountKrw: 60_000,
                displayOverride: '6.0',
                note: null,
              },
            ],
            fullSpanCells: [],
            guidanceItems: [],
          },
        ],
        footnote: null,
        mock: false,
      },
      includedItems: [
        '기본 믹싱',
        '음량과 밸런스 조정',
        '마스터 출력',
        '기본 수정',
      ],
      turnaroundLabel: '트랙 상태와 납기 확인 후 협의',
      revisionLabel: '기본 수정 범위는 납품 형식과 함께 협의',
      additionalCostNote: null,
      inquiryLabel: '믹싱 / 마스터링 문의하기',
    },
  ],

  commonNoticeHeading: '공통 안내',
  terms: [
    {
      id: 'final-price-after-consultation',
      order: 10,
      enabled: true,
      scope: 'global',
      serviceId: null,
      label: '모든 작업비용은 상의 후 최종 결정',
      description:
        '작업 범위와 일정, 사용 목적을 확인한 뒤 최종 견적을 안내합니다.',
      iconKey: 'consultation',
    },
    {
      id: 'formation-included-over-two',
      order: 20,
      enabled: true,
      scope: 'service',
      serviceId: 'choreography',
      label: '2인 이상은 동선 구성 작업 포함',
      description:
        '2인 이상 안무에는 기본 동선 구성 작업이 포함됩니다.',
      iconKey: 'people',
    },
    {
      id: 'video-planning-equipment-surcharge',
      order: 25,
      enabled: true,
      scope: 'service',
      serviceId: 'video-direction',
      label: '촬영현장 감독은 촬영장비에 따라 추가금 발생',
      description: null,
      iconKey: null,
    },
    {
      id: 'vat-included',
      order: 30,
      enabled: true,
      scope: 'global',
      serviceId: null,
      label: '부가세 포함',
      description:
        '안내된 비용은 부가가치세를 포함한 금액입니다.',
      iconKey: 'receipt',
    },
    {
      id: 'usage-adjustment',
      order: 40,
      enabled: true,
      scope: 'global',
      serviceId: null,
      label: '용도에 따라 기본가에서 조정 가능',
      description:
        '상업 사용, 광고, 행사 등 사용 범위에 따라 조정될 수 있습니다.',
      iconKey: 'adjustment',
    },
    {
      id: 'rush-fee',
      order: 50,
      enabled: true,
      scope: 'global',
      serviceId: null,
      label: '빠른 마감 추가금 발생',
      description:
        '일반 작업 일정보다 빠른 납기를 요청할 경우 추가 비용이 발생합니다.',
      iconKey: 'deadline',
    },
    {
      id: 'excessive-revision-fee',
      order: 60,
      enabled: true,
      scope: 'global',
      serviceId: null,
      label: '지나친 수정 요청 시 추가금 발생',
      description:
        '협의된 수정 범위를 넘어서는 반복 수정에는 추가 비용이 발생합니다.',
      iconKey: 'revision',
    },
  ],

  worksLinkLabel: '전체 작업 보기',
  contactLinkLabel: '프로젝트 문의',
} as const satisfies CommissionGuideContent
